//
//  databaseLink.swift
//  GoodMovieApplication
//
//  Created by hadrien de lamotte on 14/06/2017.
//  Copyright © 2017 hadrien de lamotte. All rights reserved.
//

import Foundation
import SQLite

class databaseLink: NSObject {
    
    static var db : Connection?;
    
    static func initDatabaseConnection() -> Any {
        do {
            let path = NSSearchPathForDirectoriesInDomains(
            .documentDirectory, .userDomainMask, true
            ).first!
            let db = try Connection("\(path)/db.sqlite3")
            databaseLink.db = db;
            return db;
        }
        catch let error {
            print(error);
            print(error.localizedDescription)
            return "Could not edit database";
        }
    }
    
    
    static func deleteMovietable(db : Connection) -> Bool {
        do {
            _ = try db.prepare("DROP TABLE IF EXISTS movies;")
            return true;
        }
        catch  {
            return false;
        }
    }
    
    static func getAllMovies() -> Array<MovieModel> {
        let db = databaseLink.db!;
        var movieList : Array<MovieModel> = Array<MovieModel>();
        do {
            let movies = Array(try db.prepare("SELECT * FROM movies"))
            for movie in movies {
                movieList.append(MovieModel(data: movie));
            }
        }
        catch  {}
        return movieList;
    }

    
    static func populateDB(db : Connection) -> Bool {
        do {
            try db.execute(
                "CREATE TABLE IF NOT EXISTS movies (" +
                    "id integer primary key autoincrement," +
                    "Title VARCHAR(255) NOT NULL," +
                    "Year DOUBLE NOT NULL," +
                    "Rated TEXT NOT NULL," +
                    "Released TEXT NOT NULL," +
                    "Runtime TEXT NOT NULL," +
                    "Genre TEXT NOT NULL," +
                    "Director TEXT NOT NULL," +
                    "Writer TEXT NOT NULL," +
                    "Actors TEXT NOT NULL," +
                    "Plot TEXT NOT NULL," +
                    "Language TEXT NOT NULL," +
                    "Country TEXT NOT NULL," +
                    "Awards TEXT NOT NULL," +
                    "Poster TEXT NOT NULL," +
                    "Metascore DOUBLE NOT NULL," +
                    "imdbRating TEXT NOT NULL," +
                    "imdbVotes TEXT NOT NULL," +
                    "BoxOffice TEXT NOT NULL," +
                    "Youtube TEXT NOT NULL" +
                    ");" +
                    "INSERT INTO MOVIES VALUES (NULL,'Avatar',2009,'PG-13','18 Dec 2009','162 min','Action, Adventure, Fantasy','James Cameron','James Cameron','Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang','A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.','English, Spanish','UK, USA','Won 3 Oscars. Another 82 wins & 121 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg',83,'7.8','930,353','$749,700,000','https://www.youtube.com/embed/5MB3Ea6L-gw');" +
                    "INSERT INTO MOVIES VALUES (NULL,'Pirates of the Caribbean: At Worlds End',2007,'PG-13','25 May 2007','169 min','Action, Adventure, Fantasy','Gore Verbinski','Ted Elliott, Terry Rossio, Ted Elliott (characters), Terry Rossio (characters), Stuart Beattie (characters), Jay Wolpert (characters)','Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley','Captain Barbossa, Will Turner and Elizabeth Swann must sail off the edge of the map, navigate treachery and betrayal, find Jack Sparrow, and make their final alliances for one last decisive battle.','English','USA','Nominated for 2 Oscars. Another 20 wins & 42 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjIyNjkxNzEyMl5BMl5BanBnXkFtZTYwMjc3MDE3._V1_SX300.jpg',50,'7.1','496,559','$309,404,152.00','https://www.youtube.com/embed/HKSZtp_OGHY');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Spectre',2015,'PG-13','06 Nov 2015','148 min','Action, Adventure, Thriller','Sam Mendes','John Logan (screenplay), Neal Purvis (screenplay), Robert Wade (screenplay), Jez Butterworth (screenplay), John Logan (story), Neal Purvis (story), Robert Wade (story), Ian Fleming (characters)','Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes','A cryptic message from Bonds past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.','English, Spanish, Italian, German, French','UK, USA','Won 1 Oscar. Another 7 wins & 30 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2Nzg4MzkwOF5BMl5BanBnXkFtZTgwNzA0OTE3NjE@._V1_SX300.jpg',60,'6.8','307,106','$208,777,731.00','https://www.youtube.com/embed/kQx_SrKS1sQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Dark Knight Rises',2012,'PG-13','20 Jul 2012','164 min','Action, Thriller','Christopher Nolan','Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)','Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt','Eight years after the Jokers reign of anarchy, the Dark Knight, with the help of the enigmatic Selina, is forced from his imposed exile to save Gotham City, now on the edge of total annihilation, from the brutal guerrilla terrorist Bane.','English, Arabic','UK, USA','Nominated for 1 BAFTA Film Award. Another 38 wins & 98 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg',78,'8.5','1,214,026','$448,130,642.00','https://www.youtube.com/embed/z5Humz3ONgk');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'John Carter',2012,'PG-13','09 Mar 2012','132 min','Action, Adventure, Sci-Fi','Andrew Stanton','Andrew Stanton (screenplay), Mark Andrews (screenplay), Michael Chabon (screenplay), Edgar Rice Burroughs (based on the story A Princess of Mars by)','Taylor Kitsch, Lynn Collins, Samantha Morton, Willem Dafoe','Transported to Barsoom, a Civil War vet discovers a barren planet seemingly inhabited by 12-foot tall barbarians. Finding himself prisoner of these creatures, he escapes, only to encounter Woola and a princess in desperate need of a savior.','English','USA','2 wins & 8 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BNjkyOTI5MDA0Ml5BMl5BanBnXkFtZTcwOTU3NzExNw@@._V1_SX300.jpg',51,'6.6','220,108','$73,058,679','https://www.youtube.com/embed/WR6HUkzxjR0');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Spider-Man 3',2007,'PG-13','04 May 2007','139 min','Action, Adventure','Sam Raimi','Sam Raimi (screenplay), Ivan Raimi (screenplay), Alvin Sargent (screenplay), Sam Raimi (screen story), Ivan Raimi (screen story), Stan Lee (Marvel comic book), Steve Ditko (Marvel comic book)','Tobey Maguire, Kirsten Dunst, James Franco, Thomas Haden Church','A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.','English, French','USA','Nominated for 1 BAFTA Film Award. Another 3 wins & 32 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg',59,'6.2','404,210','$336,530,303','https://www.youtube.com/embed/wPosLpgMtTY');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Tangled',2010,'PG','24 Nov 2010','100 min','Animation, Adventure, Comedy','Nathan Greno, Byron Howard','Dan Fogelman (screenplay), Jacob Grimm (based upon the fairy tale Rapunzel by), Wilhelm Grimm (based upon the fairy tale Rapunzel by)','Mandy Moore, Zachary Levi, Donna Murphy, Ron Perlman','The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.','English','USA','Nominated for 1 Oscar. Another 9 wins & 39 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTAxNDYxMjg0MjNeQTJeQWpwZ15BbWU3MDcyNTk2OTM@._V1_SX300.jpg',71,'7.8','315,297','$200,803,309','https://www.youtube.com/embed/gsYKF8ecC8g');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Avengers: Age of Ultron',2015,'PG-13','01 May 2015','141 min','Action, Adventure, Sci-Fi','Joss Whedon','Joss Whedon, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (character created by: Captain America), Jack Kirby (character created by: Captain America), Jim Starlin (character created by: Thanos)','Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans','When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and its up to Earths Mightiest Heroes to stop the villainous Ultron from enacting his terrible plans.','English','USA','5 wins & 41 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg',66,'7.4','512,191','$429,113,729','https://www.youtube.com/embed/eGwuoYKhqx8');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Harry Potter and the Half-Blood Prince',2009,'PG','15 Jul 2009','153 min','Adventure, Family, Fantasy','David Yates','Steve Kloves (screenplay), J.K. Rowling (novel)','Daniel Radcliffe, Michael Gambon, Dave Legeno, Elarica Johnson','As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as the property of the Half-Blood Prince and begins to learn more about Lord Voldemorts dark past.','English','UK, USA','Nominated for 1 Oscar. Another 8 wins & 34 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_SX300.jpg',78,'7.5','349,839','$301,920,409','https://www.youtube.com/embed/JYLdTuL9Wjw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Batman v Superman: Dawn of Justice',2016,'PG-13','25 Mar 2016','151 min','Action, Adventure, Sci-Fi','Zack Snyder','Chris Terrio, David S. Goyer, Bob Kane (Batman created by), Bill Finger (Batman created by), Jerry Siegel (Superman created by), Joe Shuster (Superman created by)','Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg','Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.','English','USA','11 wins & 29 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',44,'6.7','471,010','$293,792,936','https://www.youtube.com/embed/6as8ahAr1Uc');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Superman Returns',2006,'PG-13','28 Jun 2006','154 min','Action, Adventure, Sci-Fi','Bryan Singer','Michael Dougherty (screenplay), Dan Harris (screenplay), Bryan Singer (story), Michael Dougherty (story), Dan Harris (story), Jerry Siegel (characters), Joe Shuster (characters)','Brandon Routh, Kate Bosworth, Kevin Spacey, James Marsden','Superman reappears after a long absence, but is challenged by an old foe who uses Kryptonian technology for world domination.','English, German, French','USA','Nominated for 1 Oscar. Another 12 wins & 38 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTU3NzA5MjI0Nl5BMl5BanBnXkFtZTcwMTEwNzMzMQ@@._V1_SX300.jpg',72,'6.1','246,057','$200,100,000','https://www.youtube.com/embed/zVCozSQj8TQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Quantum of Solace',2008,'PG-13','14 Nov 2008','106 min','Action, Adventure','Marc Forster','Paul Haggis, Neal Purvis, Robert Wade','Daniel Craig, Olga Kurylenko, Mathieu Amalric, Judi Dench','James Bond descends into mystery as he tries to stop a mysterious organization from eliminating a countrys most valuable resource. All the while, he still tries to seek revenge over the death of his love.','English, Spanish, Italian, French, Swiss German, German','UK, USA','Nominated for 2 BAFTA Film Awards. Another 4 wins & 29 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0MjI4MDI5MF5BMl5BanBnXkFtZTcwODkwNjk3MQ@@._V1_SX300.jpg',58,'6.6','346,553','$168,400,000','https://www.youtube.com/embed/BBqYaFEWBxI');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Pirates of the Caribbean: Dead Mans Chest',2006,'PG-13','07 Jul 2006','151 min','Action, Adventure, Fantasy','Gore Verbinski','Ted Elliott, Terry Rossio, Ted Elliott (characters), Terry Rossio (characters), Stuart Beattie (characters), Jay Wolpert (characters)','Johnny Depp, Orlando Bloom, Keira Knightley, Jack Davenport','Jack Sparrow races to recover the heart of Davy Jones to avoid enslaving his soul to Jones service, as other friends and foes seek the heart for their own agenda as well.','English, Turkish, Greek, Mandarin, French','USA','Won 1 Oscar. Another 42 wins & 51 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwODc1MTMxM15BMl5BanBnXkFtZTYwMDg1NzY3._V1_SX300.jpg',53,'7.3','549,500','$423,032,628.00','https://www.youtube.com/embed/elqO-GNfStM');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Lone Ranger',2013,'PG-13','03 Jul 2013','150 min','Action, Adventure, Western','Gore Verbinski','Justin Haythe (screenplay), Ted Elliott (screenplay), Terry Rossio (screenplay), Ted Elliott (screen story), Terry Rossio (screen story), Justin Haythe (screen story)','Johnny Depp, Armie Hammer, William Fichtner, Tom Wilkinson','Native American warrior Tonto recounts the untold tales that transformed John Reid, a man of the law, into a legend of justice.','English, North American Indian','USA','Nominated for 2 Oscars. Another 4 wins & 17 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjI3Mjk5MTUxOV5BMl5BanBnXkFtZTcwNTMyNzY3OQ@@._V1_SX300.jpg',37,'6.5','190,540','$89,289,910','https://www.youtube.com/embed/LoVhgaj6PiE');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Man of Steel',2013,'PG-13','14 Jun 2013','143 min','Action, Adventure, Fantasy','Zack Snyder','David S. Goyer (screenplay), David S. Goyer (story), Christopher Nolan (story), Jerry Siegel (Superman created by), Joe Shuster (Superman created by)','Henry Cavill, Amy Adams, Michael Shannon, Diane Lane','Clark Kent, one of the last of an extinguished race disguised as an unremarkable human, is forced to reveal his identity when Earth is invaded by an army of survivors who threaten to bring the planet to the brink of destruction.','English','USA, Canada, UK','7 wins & 45 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjI5OTYzNjI0Ml5BMl5BanBnXkFtZTcwMzM1NDA1OQ@@._V1_SX300.jpg',55,'7.1','575,047','$291,021,565','https://www.youtube.com/embed/KVu3gS7iJu4');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Chronicles of Narnia: Prince Caspian',2008,'PG','16 May 2008','150 min','Action, Adventure, Family','Andrew Adamson','Andrew Adamson (screenplay), Christopher Markus (screenplay), Stephen McFeely (screenplay), C.S. Lewis (novel)','Ben Barnes, Georgie Henley, Skandar Keynes, William Moseley','The Pevensie siblings return to Narnia, where they are enlisted to once again help ward off an evil king and restore the rightful heir to the lands throne, Prince Caspian.','English','USA, Poland, Slovenia, Czech Republic','2 wins & 19 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTIwOTA4NTE4Ml5BMl5BanBnXkFtZTcwOTI2NTg1MQ@@._V1_SX300.jpg',62,'6.6','158,510','$141,614,023','https://www.youtube.com/embed/dSJqhmjYw-o');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Avengers',2012,'PG-13','04 May 2012','143 min','Action, Sci-Fi','Joss Whedon','Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)','Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth','Earths mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.','English, Russian, Hindi','USA','Nominated for 1 Oscar. Another 37 wins & 78 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg',69,'8.1','1,042,087','$623,279,547','https://www.youtube.com/embed/hIR8Ar-Z4hw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Pirates of the Caribbean: On Stranger Tides',2011,'PG-13','20 May 2011','136 min','Action, Adventure, Fantasy','Rob Marshall','Ted Elliott (screenplay), Terry Rossio (screenplay), Ted Elliott (screen story), Terry Rossio (screen story), Ted Elliott (characters), Terry Rossio (characters), Stuart Beattie (characters), Jay Wolpert (characters), Tim Powers (novel)','Johnny Depp, Penélope Cruz, Geoffrey Rush, Ian McShane','Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth, only to discover that Blackbeard and his daughter are after it too.','English, Spanish','USA, UK','2 wins & 31 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_SX300.jpg',45,'6.7','391,341','$241,063,875.00','https://www.youtube.com/embed/Ax6md6HoZ2o');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Men in Black 3',2012,'PG-13','25 May 2012','106 min','Action, Adventure, Comedy','Barry Sonnenfeld','Etan Cohen, Lowell Cunningham (based on the Malibu comic by)','Will Smith, Tommy Lee Jones, Josh Brolin, Jemaine Clement','Agent J travels in time to M.I.B.s early days in 1969 to stop an alien from assassinating his friend Agent K and changing history.','English, Ukrainian','USA','1 win & 13 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NTYxODcwMF5BMl5BanBnXkFtZTcwNDk1NDY0Nw@@._V1_SX300.jpg',58,'6.8','277,731','$179,020,854','https://www.youtube.com/embed/IyaFEBI_L24');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Hobbit: The Battle of the Five Armies',2014,'PG-13','17 Dec 2014','144 min','Adventure, Fantasy','Peter Jackson','Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay), Guillermo del Toro (screenplay), J.R.R. Tolkien (novel)','Ian McKellen, Martin Freeman, Richard Armitage, Ken Stott','Bilbo and Company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness.','English','New Zealand, USA','Nominated for 1 Oscar. Another 7 wins & 47 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BODAzMDgxMDc1MF5BMl5BanBnXkFtZTgwMTI0OTAzMjE@._V1_SX300.jpg',59,'7.4','383,226','$187,747,747','https://www.youtube.com/embed/ZSzeFFsKEt4');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Amazing Spider-Man',2012,'PG-13','03 Jul 2012','136 min','Action, Adventure','Marc Webb','James Vanderbilt (screenplay), Alvin Sargent (screenplay), Steve Kloves (screenplay), James Vanderbilt (story), Stan Lee (based on the Marvel comic book by), Steve Ditko (based on the Marvel comic book by)','Andrew Garfield, Emma Stone, Rhys Ifans, Denis Leary','After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to solve the mystery of his parents mysterious death.','English','USA','2 wins & 31 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_SX300.jpg',66,'7.0','472,210','$262,030,663','https://www.youtube.com/embed/-tnxzJ0SSOw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Robin Hood',2010,'PG-13','14 May 2010','140 min','Action, Adventure, Drama','Ridley Scott','Brian Helgeland (screenplay), Brian Helgeland (story), Ethan Reiff (story), Cyrus Voris (story)','Russell Crowe, Cate Blanchett, Max von Sydow, William Hurt','In 12th century England, Robin and his band of marauders confront corruption in a local village and lead an uprising against the crown that will forever alter the balance of world power.','English, French, Ukrainian','USA, UK','1 win & 16 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM5NzcwMzEwOF5BMl5BanBnXkFtZTcwNjg5MTgwMw@@._V1_SX300.jpg',53,'6.7','220,794','$105,219,735','https://www.youtube.com/embed/SmdsIIdJXrI');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Hobbit: The Desolation of Smaug',2013,'PG-13','13 Dec 2013','161 min','Adventure, Fantasy','Peter Jackson','Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay), Guillermo del Toro (screenplay), J.R.R. Tolkien (novel)','Ian McKellen, Martin Freeman, Richard Armitage, Ken Stott','The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.','English','USA, New Zealand','Nominated for 3 Oscars. Another 16 wins & 85 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_SX300.jpg',66,'7.9','512,266','$180,443,783','https://www.youtube.com/embed/1TInKozG3JU');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Golden Compass',2007,'PG-13','07 Dec 2007','113 min','Adventure, Family, Fantasy','Chris Weitz','Chris Weitz (screenplay), Philip Pullman (novel)','Nicole Kidman, Daniel Craig, Dakota Blue Richards, Ben Walker','In a parallel universe, young Lyra Belacqua journeys to the far North to save her best friend and other kidnapped children from terrible experiments by a mysterious organization.','English, Icelandic, Russian, French','UK, USA','Won 1 Oscar. Another 6 wins & 32 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2NDkxMjQxMV5BMl5BanBnXkFtZTYwNTMxMDM4._V1_SX300.jpg',51,'6.1','154,634','$70,100,000.00','https://www.youtube.com/embed/gNiiJ0JtBOQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'King Kong',2005,'PG-13','14 Dec 2005','187 min','Action, Adventure, Drama','Peter Jackson','Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay), Merian C. Cooper (based on a story by), Edgar Wallace (based on a story by)','Naomi Watts, Jack Black, Adrien Brody, Thomas Kretschmann','A movies crew, travelling to a mysterious island to shoot their picture, encounter a furious gorilla, taking their leading actress and forming a special relationship with her, protecting her at all costs.','English','New Zealand, USA, Germany','Won 3 Oscars. Another 39 wins & 92 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjYxYmRlZWYtMzAwNC00MDA1LWJjNTItOTBjMzlhNGMzYzk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',81,'7.2','333,345','$218,100,000','https://www.youtube.com/embed/AYaTCPbYGdk');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Titanic',1997,'PG-13','19 Dec 1997','194 min','Drama, Romance','James Cameron','James Cameron','Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates','A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.','English, Swedish','USA','Won 11 Oscars. Another 110 wins & 74 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',74,'7.7','838,917','N/A','https://www.youtube.com/embed/2e-eXJ6HgkQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Captain America: Civil War',2016,'PG-13','06 May 2016','147 min','Action, Adventure, Sci-Fi','Anthony Russo, Joe Russo','Christopher Markus (screenplay), Stephen McFeely (screenplay), Joe Simon (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)','Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan','Political interference in the Avengers activities causes a rift between former allies Captain America and Iron Man.','English, German, Xhosa, Russian, Romanian, Hindi','USA','6 wins & 60 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SX300.jpg',75,'7.9','402,568','$408,080,554','https://www.youtube.com/embed/43NWzay3W4s');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Battleship',2012,'PG-13','18 May 2012','131 min','Action, Adventure, Sci-Fi','Peter Berg','Jon Hoeber, Erich Hoeber','Taylor Kitsch, Alexander Skarsgord, Rihanna, Brooklyn Decker','A fleet of ships is forced to do battle with an armada of unknown origins in order to discover and thwart their destructive goals.','English, Japanese','USA','4 wins & 15 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjI5NTM5MDA2N15BMl5BanBnXkFtZTcwNjkwMzQxNw@@._V1_SX300.jpg',41,'5.8','210,007','$65,173,160','https://www.youtube.com/embed/cp3646Zf8rg');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Jurassic World',2015,'PG-13','12 Jun 2015','124 min','Action, Adventure, Sci-Fi','Colin Trevorrow','Rick Jaffa (screenplay), Amanda Silver (screenplay), Colin Trevorrow (screenplay), Derek Connolly (screenplay), Rick Jaffa (story), Amanda Silver (story), Michael Crichton (characters)','Chris Pratt, Bryce Dallas Howard, Irrfan Khan, Vincent DOnofrio','A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, which escapes containment and goes on a killing spree.','English','USA','6 wins & 53 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ5MTE0MTk3Nl5BMl5BanBnXkFtZTgwMjczMzk2NTE@._V1_SX300.jpg',59,'7.0','451,504','$528,757,749','https://www.youtube.com/embed/bvu-zlR5A8Q');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Skyfall',2012,'PG-13','09 Nov 2012','143 min','Action, Adventure, Thriller','Sam Mendes','Neal Purvis, Robert Wade, John Logan','Daniel Craig, Judi Dench, Javier Bardem, Ralph Fiennes','Bonds loyalty to M is tested when her past comes back to haunt her. Whilst MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.','English','UK, USA','Won 2 Oscars. Another 65 wins & 116 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BNDVhZmJiYWMtNmIzMC00ZWNiLTkzZDYtNGNlZmViMGM4OGExXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg',81,'7.8','545,638','$299,300,000','https://www.youtube.com/embed/6kw1UVovByw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Spider-Man 2',2004,'PG-13','30 Jun 2004','127 min','Action, Adventure','Sam Raimi','Stan Lee (comic book), Steve Ditko (comic book), Alfred Gough (screen story), Miles Millar (screen story), Michael Chabon (screen story), Alvin Sargent (screenplay)','Tobey Maguire, Kirsten Dunst, James Franco, Alfred Molina','Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius.','English, Russian, Chinese','USA','Won 1 Oscar. Another 23 wins & 55 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMzY2ODk4NmUtOTVmNi00ZTdkLTlmOWYtMmE2OWVhNTU2OTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',83,'7.3','436,144','$373,377,893','https://www.youtube.com/embed/DlM2CWNTQ84');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Iron Man 3',2013,'PG-13','03 May 2013','130 min','Action, Adventure, Sci-Fi','Shane Black','Drew Pearce (screenplay), Shane Black (screenplay), Stan Lee (based on the Marvel comic book by), Don Heck (based on the Marvel comic book by), Larry Lieber (based on the Marvel comic book by), Jack Kirby (based on the Marvel comic book by), Warren Ellis (based on the Extremis mini-series written by), Adi Granov (based on the Extremis mini-series illustrated by)','Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce','When Tony Starks world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.','English','China, USA','Nominated for 1 Oscar. Another 17 wins & 57 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzMjEzMjY1M15BMl5BanBnXkFtZTcwNTMxOTYyOQ@@._V1_SX300.jpg',62,'7.2','587,388','$408,992,272','https://www.youtube.com/embed/YLorLVa95Xo');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Alice in Wonderland',2010,'PG','05 Mar 2010','108 min','Adventure, Family, Fantasy','Tim Burton','Linda Woolverton (screenplay), Lewis Carroll (books)','Johnny Depp, Mia Wasikowska, Helena Bonham Carter, Anne Hathaway','Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny: to end the Red Queens reign of terror.','English','USA','Won 2 Oscars. Another 32 wins & 61 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNjAxMTc0Nl5BMl5BanBnXkFtZTcwODc3ODk5Mg@@._V1_SX300.jpg',53,'6.5','323,570','$319,323,000.00','https://www.youtube.com/embed/pMiCJefpn9Q');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'X-Men: The Last Stand',2006,'PG-13','26 May 2006','104 min','Action, Adventure, Fantasy','Brett Ratner','Simon Kinberg, Zak Penn','Hugh Jackman, Halle Berry, Ian McKellen, Patrick Stewart','When a cure is found to treat mutations, lines are drawn amongst the X-Men, led by Professor Charles Xavier, and the Brotherhood, a band of powerful mutants organized under Xaviers former ally, Magneto.','English','Canada, USA, UK','7 wins & 37 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTg2ODA2Nl5BMl5BanBnXkFtZTcwMDc2MjEzMw@@._V1_SX300.jpg',58,'6.7','403,650','$234,300,000','https://www.youtube.com/embed/yaqeXXuoD7I');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Monsters University',2013,'G','21 Jun 2013','104 min','Animation, Adventure, Comedy','Dan Scanlon','Dan Scanlon (story by), Daniel Gerson (story by), Robert L. Baird (story by), Daniel Gerson (screenplay), Robert L. Baird (screenplay), Dan Scanlon (screenplay)','Billy Crystal, John Goodman, Steve Buscemi, Helen Mirren','A look at the relationship between Mike and Sulley during their days at Monsters University -- when they werent necessarily the best of friends.','English','USA','Nominated for 1 BAFTA Film Award. Another 9 wins & 56 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyODgwMDU3M15BMl5BanBnXkFtZTcwOTM4MjcxOQ@@._V1_SX300.jpg',65,'7.3','251,595','$260,300,000','https://www.youtube.com/embed/JbeFIfS8uno');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Transformers: Revenge of the Fallen',2009,'PG-13','24 Jun 2009','150 min','Action, Adventure, Sci-Fi','Michael Bay','Ehren Kruger, Roberto Orci, Alex Kurtzman','Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson','Sam Witwicky leaves the Autobots behind for a normal life. But when his mind is filled with cryptic symbols, the Decepticons target him and he is dragged back into the Transformers war.','English, Spanish','USA','Nominated for 1 Oscar. Another 15 wins & 26 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BNjk4OTczOTk0NF5BMl5BanBnXkFtZTcwNjQ0NzMzMw@@._V1_SX300.jpg',35,'6.0','334,986','$402,076,689','https://www.youtube.com/embed/qSQ2xcjalHI');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Transformers: Age of Extinction',2014,'PG-13','27 Jun 2014','165 min','Action, Adventure, Sci-Fi','Michael Bay','Ehren Kruger','Mark Wahlberg, Stanley Tucci, Kelsey Grammer, Nicola Peltz','Autobots must escape sight from a bounty hunter who has taken control of the human serendipity: Unexpectedly, Optimus Prime and his remaining gang turn to a mechanic, his daughter, and her back street racing boyfriend for help.','English','USA, China','5 wins & 23 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjEwNTg1MTA5Nl5BMl5BanBnXkFtZTgwOTg2OTM4MTE@._V1_SX300.jpg',32,'5.7','254,840','$206,755,538','https://www.youtube.com/embed/EOmpqg1YoWU');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Oz the Great and Powerful',2013,'PG','08 Mar 2013','130 min','Adventure, Family, Fantasy','Sam Raimi','Mitchell Kapner (screenplay), David Lindsay-Abaire (screenplay), Mitchell Kapner (screen story), L. Frank Baum (Oz works)','James Franco, Mila Kunis, Rachel Weisz, Michelle Williams','A frustrated circus magician from Kansas is transported to a magical land called Oz, where he will have to fulfill a prophecy to become the king, and release the land from the Wicked Witches using his great (but fake) powers.','English','USA','5 wins & 31 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyMzQ1ODM1MF5BMl5BanBnXkFtZTcwMjE2MTQxOQ@@._V1_SX300.jpg',44,'6.3','181,069','$234,903,076','https://www.youtube.com/embed/yyywumlnhdw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Amazing Spider-Man 2',2014,'PG-13','02 May 2014','142 min','Action, Adventure, Sci-Fi','Marc Webb','Alex Kurtzman (screenplay), Roberto Orci (screenplay), Jeff Pinkner (screenplay), Alex Kurtzman (screen story), Roberto Orci (screen story), Jeff Pinkner (screen story), James Vanderbilt (screen story), Stan Lee (Marvel comic book), Steve Ditko (Marvel comic book)','Andrew Garfield, Emma Stone, Jamie Foxx, Dane DeHaan','When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as his loved ones.','English','USA','3 wins & 29 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BOTA5NDYxNTg0OV5BMl5BanBnXkFtZTgwODE5NzU1MTE@._V1_SX300.jpg',53,'6.7','339,837','$183,277,573','https://www.youtube.com/embed/DlM2CWNTQ84');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'TRON: Legacy',2010,'PG','17 Dec 2010','125 min','Action, Adventure, Sci-Fi','Joseph Kosinski','Edward Kitsis (screenplay), Adam Horowitz (screenplay), Edward Kitsis (story), Adam Horowitz (story), Brian Klugman (story), Lee Sternthal (story), Steven Lisberger (characters), Bonnie MacBird (characters)','Jeff Bridges, Garrett Hedlund, Olivia Wilde, Bruce Boxleitner','The son of a virtual world designer goes looking for his father and ends up inside the digital world that his father designed. He meets his fathers corrupted creation and a unique ally who was born inside the digital world.','English','USA','Nominated for 1 Oscar. Another 10 wins & 48 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4NTk4MTk1OF5BMl5BanBnXkFtZTcwNTE2MDIwNA@@._V1_SX300.jpg',49,'6.8','272,798','$172,051,787.00','https://www.youtube.com/embed/L9szn1QQfas');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Cars 2',2011,'G','24 Jun 2011','106 min','Animation, Adventure, Comedy','John Lasseter, Brad Lewis','John Lasseter (original story by), Brad Lewis (original story by), Dan Fogelman (original story by), Ben Queen (screenplay)','Larry the Cable Guy, Owen Wilson, Michael Caine, Emily Mortimer','Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.','English, Japanese, Italian, French','USA','Nominated for 1 Golden Globe. Another 1 win & 18 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTUzNTc3MTU3M15BMl5BanBnXkFtZTcwMzIxNTc3NA@@._V1_SX300.jpg',57,'6.2','110,076','$191,450,875','https://www.youtube.com/embed/zGeLIDJ9zEk');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Green Lantern',2011,'PG-13','17 Jun 2011','114 min','Action, Adventure, Sci-Fi','Martin Campbell','Greg Berlanti (screenplay), Michael Green (screenplay), Marc Guggenheim (screenplay), Michael Goldenberg (screenplay), Greg Berlanti (screen story), Michael Green (screen story), Marc Guggenheim (screen story)','Ryan Reynolds, Blake Lively, Peter Sarsgaard, Mark Strong','Reckless test pilot Hal Jordan is granted an alien ring that bestows him with otherworldly powers that inducts him into an intergalactic police force, the Green Lantern Corps.','English','USA','3 wins & 5 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTMyMTg3OTM5Ml5BMl5BanBnXkFtZTcwNzczMjEyNQ@@._V1_SX300.jpg',39,'5.6','231,015','$116,600,000','https://www.youtube.com/embed/W7w07MLhhb4');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Toy Story 3',2010,'G','18 Jun 2010','103 min','Animation, Adventure, Comedy','Lee Unkrich','John Lasseter (story by), Andrew Stanton (story by), Lee Unkrich (story by), Michael Arndt (screenplay)','Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty','The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and its up to Woody to convince the other toys that they werent abandoned and to return home.','English, Spanish','USA','Won 2 Oscars. Another 58 wins & 89 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg',92,'8.3','581,497','$414,984,497','https://www.youtube.com/embed/TNMpa5yBf5o');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Terminator Salvation',2009,'PG-13','21 May 2009','115 min','Action, Adventure, Drama','McG','John Brancato, Michael Ferris','Christian Bale, Sam Worthington, Moon Bloodgood, Helena Bonham Carter','In 2018, a mysterious new weapon in the war against the machines, half-human and half-machine, comes to John Connor on the eve of a resistance attack on Skynet. But whose side is he on, and can he be trusted?','English, Italian','USA, Germany, UK, Italy','2 wins & 12 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BODE1MTM1MzA2NF5BMl5BanBnXkFtZTcwODQ5MTA2Mg@@._V1_SX300.jpg',49,'6.6','295,747','$125,286,889','https://www.youtube.com/embed/Sv6SM0w0B5A');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Furious 7',2015,'PG-13','03 Apr 2015','137 min','Action, Crime, Thriller','James Wan','Chris Morgan, Gary Scott Thompson (characters)','Vin Diesel, Paul Walker, Jason Statham, Michelle Rodriguez','Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.','English','USA, Japan','Nominated for 1 Golden Globe. Another 23 wins & 26 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQxOTA2NDUzOV5BMl5BanBnXkFtZTgwNzY2MTMxMzE@._V1_SX300.jpg',67,'7.2','298,730','$316,986,481','https://www.youtube.com/embed/Skpu5HaVkOc');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'World War Z',2013,'PG-13','21 Jun 2013','116 min','Action, Adventure, Horror','Marc Forster','Matthew Michael Carnahan (screenplay), Drew Goddard (screenplay), Damon Lindelof (screenplay), Matthew Michael Carnahan (screen story), J. Michael Straczynski (screen story), Max Brooks (based on the novel by)','Brad Pitt, Mireille Enos, Daniella Kertesz, James Badge Dale','Former United Nations employee Gerry Lane traverses the world in a race against time to stop the Zombie pandemic that is toppling armies and governments, and threatening to destroy humanity itself.','English, Spanish, Hebrew, Arabic','USA','3 wins & 24 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0NTgxMjIxOF5BMl5BanBnXkFtZTcwMDM0MDY1OQ@@._V1_SX300.jpg',63,'7.0','491,982','$202,351,611','https://www.youtube.com/embed/sGf_WdlHTqs');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'X-Men: Days of Future Past',2014,'PG-13','23 May 2014','132 min','Action, Adventure, Sci-Fi','Bryan Singer','Simon Kinberg (screenplay), Jane Goldman (story by), Simon Kinberg (story by), Matthew Vaughn (story by)','Hugh Jackman, James McAvoy, Michael Fassbender, Jennifer Lawrence','The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom for both humans and mutants.','English, Vietnamese, French','USA, UK, Canada','Nominated for 1 Oscar. Another 15 wins & 46 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BZGIzNWYzN2YtMjcwYS00YjQ3LWI2NjMtOTNiYTUyYjE2MGNkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',74,'8.0','550,731','$199,305,306','https://www.youtube.com/embed/gsjtg7m1MMM');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Star Trek Into Darkness',2013,'PG-13','16 May 2013','132 min','Action, Adventure, Sci-Fi','J.J. Abrams','Roberto Orci, Alex Kurtzman, Damon Lindelof, Gene Roddenberry (television series Star Trek)','Chris Pine, Zachary Quinto, Zoe Saldana, Karl Urban','After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction.','English, Klingon','USA','Nominated for 1 Oscar. Another 6 wins & 51 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NzczOTgxNF5BMl5BanBnXkFtZTcwODQ5ODczOQ@@._V1_SX300.jpg',72,'7.8','416,482','$228,756,232','https://www.youtube.com/embed/MPLogYa9Q0o');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Jack the Giant Slayer',2013,'PG-13','01 Mar 2013','114 min','Adventure, Fantasy','Bryan Singer','Darren Lemke (screenplay), Christopher McQuarrie (screenplay), Dan Studney (screenplay), Darren Lemke (story), David Dobkin (story)','Nicholas Hoult, Eleanor Tomlinson, Ewan McGregor, Stanley Tucci','The ancient war between humans and a race of giants is reignited when Jack, a young farmhand fighting for a kingdom and the love of a princess, opens a gateway between the two worlds.','English','USA','1 win & 4 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjE1NDMxMjI0OV5BMl5BanBnXkFtZTcwMjQyMDExOQ@@._V1_SX300.jpg',51,'6.3','111,481','$65,171,860','https://www.youtube.com/embed/bXAwGb6_nEE');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Great Gatsby',2013,'PG-13','10 May 2013','143 min','Drama, Romance','Baz Luhrmann','Baz Luhrmann (screenplay), Craig Pearce (screenplay), F. Scott Fitzgerald (based on the novel by)','Lisa Adam, Frank Aldridge, Amitabh Bachchan, Steve Bisley','A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.','English','Australia, USA','Won 2 Oscars. Another 46 wins & 82 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_SX300.jpg',55,'7.3','385,340','$144,812,796','https://www.youtube.com/embed/ozkOhXmijtk');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Prince of Persia: The Sands of Time',2010,'PG-13','28 May 2010','116 min','Action, Adventure, Fantasy','Mike Newell','Boaz Yakin (screenplay), Doug Miro (screenplay), Carlo Bernard (screenplay), Jordan Mechner (screen story), Jordan Mechner (video game series Prince of Persia)','Jake Gyllenhaal, Gemma Arterton, Ben Kingsley, Alfred Molina','A young fugitive prince and princess must stop a villain who unknowingly threatens to destroy the world with a special dagger that enables the magic sand inside to reverse time.','English','USA','1 win & 9 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNDg0NzcyMV5BMl5BanBnXkFtZTcwNjg4MjQyMw@@._V1_SX300.jpg',50,'6.6','232,673','$90,755,643.00','https://www.youtube.com/embed/bZ7Li5w2I-k');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Pacific Rim',2013,'PG-13','12 Jul 2013','131 min','Action, Adventure, Sci-Fi','Guillermo del Toro','Travis Beacham (screenplay), Guillermo del Toro (screenplay), Travis Beacham (story)','Charlie Hunnam, Diego Klattenhoff, Idris Elba, Rinko Kikuchi','As a war between humankind and monstrous sea creatures wages on, a former pilot and a trainee are paired up to drive a seemingly obsolete special weapon in a desperate effort to save the world from the apocalypse.','English, Japanese, Cantonese, Mandarin','USA','Nominated for 1 BAFTA Film Award. Another 6 wins & 46 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3MTI5NjQ4Nl5BMl5BanBnXkFtZTcwOTU1OTU0OQ@@._V1_SX300.jpg',64,'7.0','398,198','$101,785,482','https://www.youtube.com/embed/zA92Rw6kNWw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Transformers: Dark of the Moon',2011,'PG-13','29 Jun 2011','154 min','Action, Adventure, Sci-Fi','Michael Bay','Ehren Kruger','Shia LaBeouf, Rosie Huntington-Whiteley, Josh Duhamel, John Turturro','The Autobots learn of a Cybertronian spacecraft hidden on the moon, and race against the Decepticons to reach it and to learn its secrets.','English','USA','Nominated for 3 Oscars. Another 10 wins & 41 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTkwOTY0MTc1NV5BMl5BanBnXkFtZTcwMDQwNjA2NQ@@._V1_SX300.jpg',42,'6.3','336,983','$352,358,779','https://www.youtube.com/embed/CtoteniC9sg');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Indiana Jones and the Kingdom of the Crystal Skull',2008,'PG-13','22 May 2008','122 min','Action, Adventure, Fantasy','Steven Spielberg','David Koepp (screenplay), George Lucas (story), Jeff Nathanson (story), George Lucas (characters), Philip Kaufman (characters)','Harrison Ford, Cate Blanchett, Karen Allen, Shia LaBeouf','Famed archaeologist/adventurer Dr. Henry Indiana Jones is called back into action when he becomes entangled in a Soviet plot to uncover the secret behind mysterious artifacts known as the Crystal Skulls.','English, German, Russian','USA','Nominated for 1 BAFTA Film Award. Another 10 wins & 34 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTIxNDUxNzcyMl5BMl5BanBnXkFtZTcwNTgwOTI3MQ@@._V1_SX300.jpg',65,'6.2','349,595','$316,957,122.00','https://www.youtube.com/embed/gQT5k8qsI34');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Good Dinosaur',2015,'PG','25 Nov 2015','93 min','Animation, Adventure, Comedy','Peter Sohn','Bob Peterson (original concept & development by), Peter Sohn (story by), Erik Benson (story by), Meg LeFauve (story by), Kelsey Mann (story by), Bob Peterson (story by), Meg LeFauve (screenplay), Peter Hedges (additional screenplay material by), Adrian Molina (additional screenplay material by)','Jeffrey Wright, Frances McDormand, Maleah Nipay-Padilla, Ryan Teeple','In a world where dinosaurs and humans live side-by-side, an Apatosaurus named Arlo makes an unlikely human friend.','English','USA','Nominated for 1 Golden Globe. Another 5 wins & 38 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MTg2NjQ4MV5BMl5BanBnXkFtZTgwNzcxOTY5NjE@._V1_SX300.jpg',66,'6.8','76,695','$94,166,454','https://www.youtube.com/embed/O-RgquKVTPE');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Brave',2012,'PG','22 Jun 2012','93 min','Animation, Adventure, Comedy','Mark Andrews, Brenda Chapman, Steve Purcell','Brenda Chapman (story by), Mark Andrews (screenplay), Steve Purcell (screenplay), Brenda Chapman (screenplay), Irene Mecchi (screenplay)','Kelly Macdonald, Billy Connolly, Emma Thompson, Julie Walters','Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.','English','USA','Won 1 Oscar. Another 18 wins & 48 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_SX300.jpg',69,'7.2','291,570','$237,282,182','https://www.youtube.com/embed/TEHWDA_6e3M');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Star Trek Beyond',2016,'PG-13','22 Jul 2016','122 min','Action, Adventure, Sci-Fi','Justin Lin','Simon Pegg, Doug Jung, Gene Roddenberry (based upon Star Trek created by)','Chris Pine, Zachary Quinto, Karl Urban, Zoe Saldana','The USS Enterprise crew explores the furthest reaches of uncharted space, where they encounter a new ruthless enemy who puts them and everything the Federation stands for to the test.','English','USA, Hong Kong, China','Nominated for 1 Oscar. Another 1 win & 23 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BZDRiOGE5ZTctOWIxOS00MWQwLThlMDYtNWIwMDQwNzBjZDY1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',68,'7.1','163,086','$158,804,470','https://www.youtube.com/embed/XRVD32rnzOw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Rush Hour 3',2007,'PG-13','10 Aug 2007','91 min','Action, Comedy, Crime','Brett Ratner','Jeff Nathanson, Ross LaManna (characters)','Chris Tucker, Jackie Chan, Max von Sydow, Hiroyuki Sanada','After an attempted assassination on Ambassador Han, Lee and Carter head to Paris to protect a French woman with knowledge of the Triads secret leaders.','English, French, Japanese, Mandarin, Latin','USA, Germany','9 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0Nzg5NjQ0MDBeQTJeQWpwZ15BbWU3MDE4Mzg5NDE@._V1_SX300.jpg',44,'6.2','127,150','$140,080,850.00','https://www.youtube.com/embed/sKf4ef4j6qQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, '2012',2009,'PG-13','13 Nov 2009','158 min','Action, Adventure, Sci-Fi','Roland Emmerich','Roland Emmerich, Harald Kloser','John Cusack, Amanda Peet, Chiwetel Ejiofor, Thandie Newton','A frustrated writer struggles to keep his family alive when a series of global catastrophes threatens to annihilate mankind.','English, French, Tibetan, Mandarin, Russian, Hindi, Portuguese, Latin, Italian','USA','5 wins & 20 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0MjEyODQzMF5BMl5BanBnXkFtZTcwMTczMjQ4Mg@@._V1_SX300.jpg',49,'5.8','297,440','$166,112,167','https://www.youtube.com/embed/sFXGrTng0gQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'A Christmas Carol',2009,'PG','06 Nov 2009','96 min','Animation, Drama, Family','Robert Zemeckis','Robert Zemeckis (screenplay), Charles Dickens (novel)','Jim Carrey, Steve Valentine, Daryl Sabara, Sage Ryan','An animated retelling of Charles Dickens classic novel about a Victorian-era miser taken on a journey of self-redemption, courtesy of several mysterious Christmas apparitions.','English','USA','3 wins & 4 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1MTI5ODU4MV5BMl5BanBnXkFtZTcwNTYyNTU4Mg@@._V1_SX300.jpg',55,'6.8','79,064','$137,816,456','https://www.youtube.com/embed/VZ3lr3urgDU');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Jupiter Ascending',2015,'PG-13','06 Feb 2015','127 min','Action, Adventure, Sci-Fi','Lana Wachowski, Lilly Wachowski','Lilly Wachowski, Lana Wachowski','Mila Kunis, Channing Tatum, Sean Bean, Eddie Redmayne','A young woman discovers her destiny as an heiress of intergalactic nobility and must fight to protect the inhabitants of Earth from an ancient and destructive industry.','English, Russian','USA, Australia','4 wins & 14 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyNzk2MjA2NF5BMl5BanBnXkFtZTgwMjEwNzk3MjE@._V1_SX300.jpg',40,'5.4','149,300','$43,733,037.00','https://www.youtube.com/embed/THVFkk-sEus');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',2005,'PG','09 Dec 2005','143 min','Adventure, Family, Fantasy','Andrew Adamson','Ann Peacock (screenplay), Andrew Adamson (screenplay), Christopher Markus (screenplay), Stephen McFeely (screenplay), C.S. Lewis (book)','Georgie Henley, Skandar Keynes, William Moseley, Anna Popplewell','Four kids travel through a wardrobe to the land of Narnia and learn of their destiny to free it with the guidance of a mystical lion.','English, German','USA, UK','Won 1 Oscar. Another 14 wins & 45 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NTUwMTU5OV5BMl5BanBnXkFtZTcwNjAwNzQzMw@@._V1_SX300.jpg',75,'6.9','303,386','$291,685,219','https://www.youtube.com/embed/ruGHxmjQ180');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'X-Men: Apocalypse',2016,'PG-13','27 May 2016','144 min','Action, Adventure, Sci-Fi','Bryan Singer','Simon Kinberg (screenplay), Bryan Singer (story by), Simon Kinberg (story by), Michael Dougherty (story by), Dan Harris (story by)','James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult','After the re-emergence of the worlds first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.','English, Polish, German, Arabic, Egyptian (Ancient)','USA','13 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjU1ODM1MzYxN15BMl5BanBnXkFtZTgwOTA4NDE2ODE@._V1_SX300.jpg',52,'7.1','272,645','$135,729,385','https://www.youtube.com/embed/Jer8XjMrUB4');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Dark Knight',2008,'PG-13','18 Jul 2008','152 min','Action, Crime, Drama','Christopher Nolan','Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)','Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the Dark Knight must come to terms with one of the greatest psychological tests of his ability to fight injustice.','English, Mandarin','USA, UK','Won 2 Oscars. Another 147 wins & 144 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',82,'9.0','1,780,245','$533,316,061','https://www.youtube.com/embed/kmJLuwP3MbY');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Up',2009,'PG','29 May 2009','96 min','Animation, Adventure, Comedy','Pete Docter, Bob Peterson','Pete Docter (story by), Bob Peterson (story by), Tom McCarthy (story by), Bob Peterson (screenplay), Pete Docter (screenplay)','Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson','Seventy-eight year old Carl Fredricksen travels to Paradise Falls in his home equipped with balloons, inadvertently taking a young stowaway.','English','USA','Won 2 Oscars. Another 74 wins & 78 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg',88,'8.3','717,289','$292,979,556','https://www.youtube.com/embed/Ajcdb4FAL7A');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Monsters vs. Aliens',2009,'PG','27 Mar 2009','94 min','Animation, Action, Adventure','Rob Letterman, Conrad Vernon','Maya Forbes (screenplay), Wallace Wolodarsky (screenplay), Rob Letterman (screenplay), Jonathan Aibel (screenplay), Glenn Berger (screenplay), Rob Letterman (story), Conrad Vernon (story)','Reese Witherspoon, Seth Rogen, Hugh Laurie, Will Arnett','A woman transformed into a giant after she is struck by a meteorite on her wedding day becomes part of a team of monsters sent in by the U.S. government to defeat an alien mastermind trying to take over Earth.','English','USA','3 wins & 9 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0OTQ3MzE3MV5BMl5BanBnXkFtZTcwMDQyMzMzMg@@._V1_SX300.jpg',56,'6.5','120,914','$198,332,128.00','https://www.youtube.com/embed/bxLAH3M3ywM');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Iron Man',2008,'PG-13','02 May 2008','126 min','Action, Adventure, Sci-Fi','Jon Favreau','Mark Fergus (screenplay), Hawk Ostby (screenplay), Art Marcum (screenplay), Matt Holloway (screenplay), Stan Lee (characters), Don Heck (characters), Larry Lieber (characters), Jack Kirby (characters)','Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow','After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.','English, Persian, Urdu, Arabic, Hungarian','USA','Nominated for 2 Oscars. Another 19 wins & 61 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg',79,'7.9','733,549','$318,298,180','https://www.youtube.com/embed/KAE5ymVLmZg');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Hugo',2011,'PG','23 Nov 2011','126 min','Adventure, Drama, Family','Martin Scorsese','John Logan (screenplay), Brian Selznick (book)','Ben Kingsley, Sacha Baron Cohen, Asa Butterfield, Chloé Grace Moretz','In Paris in 1931, an orphan named Hugo Cabret who lives in the walls of a train station is wrapped up in a mystery involving his late father and an automaton.','English','USA','Won 5 Oscars. Another 56 wins & 174 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzNzk5MzgyNF5BMl5BanBnXkFtZTcwOTE4NDU5Ng@@._V1_SX300.jpg',83,'7.5','258,205','$73,820,094','https://www.youtube.com/embed/Hv3obL9HqyY');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Wild Wild West',1999,'PG-13','30 Jun 1999','106 min','Action, Comedy, Sci-Fi','Barry Sonnenfeld','Jim Thomas (story), John Thomas (story), S.S. Wilson (screenplay), Brent Maddock (screenplay), Jeffrey Price (screenplay), Peter S. Seaman (screenplay)','Will Smith, Kevin Kline, Kenneth Branagh, Salma Hayek','The two best hired guns in the West must save President Grant from the clutches of a nineteenth-century inventor-villain.','English','USA','12 wins & 15 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BYmYyMTc4YjItMGNhNC00OWQwLWJhMWUtNTdjZDgxMDI5MjE2L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',38,'4.8','133,833','N/A','https://www.youtube.com/embed/mLkSl0dKOsI');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Mummy: Tomb of the Dragon Emperor',2008,'PG-13','01 Aug 2008','112 min','Action, Adventure, Fantasy','Rob Cohen','Alfred Gough, Miles Millar','Brendan Fraser, Jet Li, Maria Bello, John Hannah','In the Far East, Alex OConnell, the son of famed mummy fighters Rick and Evy OConnell, unearths the mummy of the first Emperor of Qin -- a shape-shifting entity cursed by a witch centuries ago.','English, Mandarin, Sanskrit','USA, Germany, China','2 wins & 6 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTU4NDIzMDY1OV5BMl5BanBnXkFtZTcwNjQxMzk3MQ@@._V1_SX300.jpg',31,'5.2','124,276','$101,600,000','https://www.youtube.com/embed/ol-U0ibnVD4');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Suicide Squad',2016,'PG-13','05 Aug 2016','123 min','Action, Adventure, Fantasy','David Ayer','David Ayer','Will Smith, Jaime FitzSimons, Ike Barinholtz, Margot Robbie','A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.','English, Japanese, Spanish','USA','Won 1 Oscar. Another 12 wins & 28 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_SX300.jpg',40,'6.3','379,107','$325,021,779','https://www.youtube.com/embed/PLLQK9la6Go');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Evan Almighty',2007,'PG','22 Jun 2007','96 min','Comedy, Family, Fantasy','Tom Shadyac','Steve Oedekerk (screenplay), Steve Oedekerk (story), Joel Cohen (story), Alec Sokolow (story), Steve Koren (characters), Mark OKeefe (characters)','Steve Carell, Morgan Freeman, Lauren Graham, Johnny Simmons','God contacts Congressman Evan Baxter and tells him to build an ark in preparation for a great flood.','English','USA','2 wins & 11 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxMTEzODYxMV5BMl5BanBnXkFtZTcwNzQ4ODU0MQ@@._V1_SX300.jpg',37,'5.4','119,435','$100,289,690','https://www.youtube.com/embed/R1QArbkQsVw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Edge of Tomorrow',2014,'PG-13','06 Jun 2014','113 min','Action, Adventure, Sci-Fi','Doug Liman','Christopher McQuarrie (screenplay), Jez Butterworth (screenplay), John-Henry Butterworth (screenplay), Hiroshi Sakurazaka (novel)','Tom Cruise, Emily Blunt, Brendan Gleeson, Bill Paxton','A soldier fighting aliens gets to relive the same day over and over again, the day restarting every time he dies.','English','USA, Canada','11 wins & 36 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5OTk4MTM3M15BMl5BanBnXkFtZTgwODcxNjg3MDE@._V1_SX300.jpg',71,'7.9','468,438','$77,121,429','https://www.youtube.com/embed/yUmSVcttXnI');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Waterworld',1995,'PG-13','28 Jul 1995','135 min','Action, Adventure, Sci-Fi','Kevin Reynolds','Peter Rader, David Twohy','Kevin Costner, Chaim Jeraffi, Rick Aviles, R.D. Call','In a future where the polar ice-caps have melted and Earth is almost entirely submerged, a mutated mariner fights starvation and outlaw smokers, and reluctantly helps a woman and a young girl try to find dry land.','English','USA','Nominated for 1 Oscar. Another 5 wins & 8 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BYzE4NTRmMDYtNWYzYi00YmNkLTk4NDEtYjFmMDc4ODQ3ODY2XkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SX300.jpg',56,'6.1','150,633','N/A','https://www.youtube.com/embed/oEp382HIisE');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'G.I. Joe: The Rise of Cobra',2009,'PG-13','07 Aug 2009','118 min','Action, Adventure, Sci-Fi','Stephen Sommers','Stuart Beattie (screenplay), David Elliot (screenplay), Paul Lovett (screenplay), Michael B. Gordon (story), Stuart Beattie (story), Stephen Sommers (story)','Adewale Akinnuoye-Agbaje, Christopher Eccleston, Grégory Fitoussi, Joseph Gordon-Levitt','An elite military unit comprised of special operatives known as G.I. Joe, operating out of The Pit, takes on an evil organization led by a notorious arms dealer.','English, French, Scottish Gaelic','USA, Czech Republic','3 wins & 17 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQzMTU1NzQwNl5BMl5BanBnXkFtZTcwNDg4NzMzMw@@._V1_SX300.jpg',32,'5.8','179,603','$150,167,630','https://www.youtube.com/embed/aFtzNHTB4C0');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Inside Out',2015,'PG','19 Jun 2015','95 min','Animation, Adventure, Comedy','Pete Docter, Ronnie Del Carmen','Pete Docter (original story by), Ronnie Del Carmen (original story by), Pete Docter (screenplay), Meg LeFauve (screenplay), Josh Cooley (screenplay), Michael Arndt (additional story material by), Bill Hader (additional dialogue by), Amy Poehler (additional dialogue by), Simon Rich (additional story material by)','Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader','After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.','English','USA','Won 1 Oscar. Another 91 wins & 95 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg',94,'8.2','410,309','$264,317,903','https://www.youtube.com/embed/yRUAzGQ3nSY');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Jungle Book',2016,'PG','15 Apr 2016','106 min','Adventure, Drama, Family','Jon Favreau','Justin Marks (screenplay), Rudyard Kipling (based on the books by)','Neel Sethi, Bill Murray, Ben Kingsley, Idris Elba','After a threat from the tiger Shere Khan forces him to flee the jungle, a man-cub named Mowgli embarks on a journey of self discovery with the help of panther, Bagheera, and free spirited bear, Baloo.','English','UK, USA','Won 1 Oscar. Another 21 wins & 43 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3NTUzNTI4MV5BMl5BanBnXkFtZTgwNjU0NjU5NzE@._V1_SX300.jpg',77,'7.5','196,263','$363,995,937.00','https://www.youtube.com/embed/HcgJRQWxKnw');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Iron Man 2',2010,'PG-13','07 May 2010','124 min','Action, Adventure, Sci-Fi','Jon Favreau','Justin Theroux (screenplay), Stan Lee (Marvel comic book), Don Heck (Marvel comic book), Larry Lieber (Marvel comic book), Jack Kirby (Marvel comic book)','Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson','With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his fathers legacy.','English, French, Russian','USA','Nominated for 1 Oscar. Another 7 wins & 40 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg',57,'7.0','552,306','$312,057,433','https://www.youtube.com/embed/BoohRoVA9WQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Snow White and the Huntsman',2012,'PG-13','01 Jun 2012','127 min','Action, Adventure, Drama','Rupert Sanders','Evan Daugherty (screenplay), John Lee Hancock (screenplay), Hossein Amini (screenplay), Evan Daugherty (screen story)','Kristen Stewart, Chris Hemsworth, Charlize Theron, Sam Claflin','In a twist to the fairy tale, the Huntsman ordered to take Snow White into the woods to be killed winds up becoming her protector and mentor in a quest to vanquish the Evil Queen.','English','USA','Nominated for 2 Oscars. Another 13 wins & 31 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1NDA0MTk5OV5BMl5BanBnXkFtZTcwMTM4NDMwNw@@._V1_SX300.jpg',57,'6.1','239,042','$155,081,785','https://www.youtube.com/embed/VY67V0wOlz8');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Maleficent',2014,'PG','30 May 2014','97 min','Action, Adventure, Family','Robert Stromberg','Linda Woolverton (screenplay), Charles Perrault (based on La Belle au bois dormant written by)','Angelina Jolie, Elle Fanning, Sharlto Copley, Lesley Manville','A vengeful fairy is driven to curse an infant princess, only to discover that the child may be the one person who can restore peace to their troubled land.','English','USA','Nominated for 1 Oscar. Another 10 wins & 41 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjAwMzAzMzExOF5BMl5BanBnXkFtZTgwOTcwMDA5MTE@._V1_SX300.jpg',56,'7.0','268,143','$190,871,149','https://www.youtube.com/embed/w-XO4XiRop0');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Dawn of the Planet of the Apes',2014,'PG-13','11 Jul 2014','130 min','Action, Adventure, Drama','Matt Reeves','Mark Bomback, Rick Jaffa, Amanda Silver, Rick Jaffa (characters), Amanda Silver (characters), Pierre Boulle (novel)','Andy Serkis, Jason Clarke, Gary Oldman, Keri Russell','A growing nation of genetically evolved apes led by Caesar is threatened by a band of human survivors of the devastating virus unleashed a decade earlier.','English, American Sign Language','USA','Nominated for 1 Oscar. Another 16 wins & 47 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTgwODk3NDc1N15BMl5BanBnXkFtZTgwNTc1NjQwMjE@._V1_SX300.jpg',79,'7.6','337,194','$183,278,877.00','https://www.youtube.com/embed/DpSaTrW4leg');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Lovers',1958,'NOT RATED','26 Oct 1959','90 min','Drama, Romance','Louis Malle','Louise de Vilmorin (dialogue)','Jeanne Moreau, Jean-Marc Bory, Judith Magre, José Luis de Vilallonga','Saddled with a dull husband and a foolish lover, a woman has an affair with a stranger.','French','France','2 wins & 1 nomination.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTI3NTkyNzU5MF5BMl5BanBnXkFtZTcwNjUzNjE2MQ@@._V1_SX300.jpg',0,'7.3','3,571','N/A','https://www.youtube.com/embed/0sgAgzTmq0k');" +
                    "INSERT INTO MOVIES VALUES (NULL, '47 Ronin',2013,'PG-13','25 Dec 2013','128 min','Action, Adventure, Drama','Carl Rinsch','Chris Morgan (screenplay), Hossein Amini (screenplay), Chris Morgan (screen story by), Walter Hamada (screen story by)','Keanu Reeves, Hiroyuki Sanada, Ko Shibasaki, Tadanobu Asano','A band of samurai set out to avenge the death and dishonor of their master at the hands of a ruthless shogun.','English, Japanese','USA','5 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0MjE2NzE0OV5BMl5BanBnXkFtZTgwNTU5MjE1MDE@._V1_SX300.jpg',28,'6.3','123,023','$20,518,224','https://www.youtube.com/embed/DEoDulGTElE');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Captain America: The Winter Soldier',2014,'PG-13','04 Apr 2014','136 min','Action, Adventure, Sci-Fi','Anthony Russo, Joe Russo','Christopher Markus (screenplay), Stephen McFeely (screenplay), Joe Simon (based on the Marvel comic by), Jack Kirby (based on the Marvel comic by)','Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford','As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.','English, French','USA','Nominated for 1 Oscar. Another 5 wins & 49 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SX300.jpg',70,'7.8','537,715','$228,636,083','https://www.youtube.com/embed/tbayiPxkUMM');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Shrek Forever After',2010,'PG','21 May 2010','93 min','Animation, Adventure, Comedy','Mike Mitchell','William Steig (book), Josh Klausner, Darren Lemke','Mike Myers, Eddie Murphy, Cameron Diaz, Antonio Banderas','Rumpelstiltskin tricks a mid-life crisis burdened Shrek into allowing himself to be erased from existence and cast in a dark alternate timeline where Rumpel rules supreme.','English','USA','1 win & 12 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0OTU1NzkxMl5BMl5BanBnXkFtZTcwMzI2NDUzMw@@._V1_SX300.jpg',58,'6.3','146,478','$238,319,043','https://www.youtube.com/embed/WV8bbMxPBdc');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Tomorrowland',2015,'PG','22 May 2015','130 min','Action, Adventure, Family','Brad Bird','Damon Lindelof (screenplay), Brad Bird (screenplay), Damon Lindelof (story by), Brad Bird (story by), Jeff Jensen (story by)','George Clooney, Hugh Laurie, Britt Robertson, Raffey Cassidy','Bound by a shared destiny, a teen bursting with scientific curiosity and a former boy-genius inventor embark on a mission to unearth the secrets of a place somewhere in time and space that exists in their collective memory.','English, French, Japanese','USA, Spain','2 wins & 16 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ0MDc5MjAyNF5BMl5BanBnXkFtZTgwMzU5Mzk1NjE@._V1_SX300.jpg',60,'6.5','141,804','$71,526,443','https://www.youtube.com/embed/1k59gXTWf-A');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Big Hero 6',2014,'PG','07 Nov 2014','102 min','Animation, Action, Adventure','Don Hall, Chris Williams','Jordan Roberts (screenplay), Robert L. Baird (screenplay), Daniel Gerson (screenplay), Man of Action (Big Hero 6 team and characters created by), Steven T. Seagle (characters), Duncan Rouleau (characters), Joe Kelly (characters), Joe Casey (characters)','Scott Adsit, Ryan Potter, Daniel Henney, T.J. Miller','The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.','English','USA','Won 1 Oscar. Another 13 wins & 55 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_SX300.jpg',74,'7.8','307,111','N/A','https://www.youtube.com/embed/z3biFxZIJOQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Wreck-It Ralph',2012,'PG','02 Nov 2012','101 min','Animation, Adventure, Comedy','Rich Moore','Rich Moore (story by), Phil Johnston (story by), Jim Reardon (story by), Phil Johnston (screenplay), Jennifer Lee (screenplay), John C. Reilly (additional story material by), Sam Levine (additional story material by), Jared Stern (additional story material by)','John C. Reilly, Sarah Silverman, Jack McBrayer, Jane Lynch','A video game villain wants to be a hero and sets out to fulfill his dream, but his quest brings havoc to the whole arcade where he lives.','English','USA','Nominated for 1 Oscar. Another 33 wins & 40 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BNzMxNTExOTkyMF5BMl5BanBnXkFtZTcwMzEyNDc0OA@@._V1_SX300.jpg',72,'7.8','289,300','$189,412,677','https://www.youtube.com/embed/JPSQOomMWro');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'The Polar Express',2004,'G','10 Nov 2004','100 min','Animation, Adventure, Family','Robert Zemeckis','Chris Van Allsburg (book), Robert Zemeckis (screenplay), William Broyles Jr. (screenplay)','Tom Hanks, Leslie Zemeckis, Eddie Deezen, Nona Gaye','A young boy embarks on a magical adventure to the North Pole on the Polar Express. During his adventure he learns about friendship, bravery, and the spirit of Christmas.','English','USA','Nominated for 3 Oscars. Another 5 wins & 22 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1NTU0NTE4MV5BMl5BanBnXkFtZTcwMTQ0MjEzMw@@._V1_SX300.jpg',61,'6.6','130,808','$162,800,000','https://www.youtube.com/embed/F8_GUrqe5tc');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Independence Day: Resurgence',2016,'PG-13','24 Jun 2016','120 min','Action, Adventure, Sci-Fi','Roland Emmerich','Nicolas Wright (screenplay), James A. Woods (screenplay), Dean Devlin (screenplay), Roland Emmerich (screenplay), James Vanderbilt (screenplay), Dean Devlin (story by), Roland Emmerich (story by), Nicolas Wright (story by), James A. Woods (story by), Dean Devlin (based on characters created by), Roland Emmerich (based on characters created by)','Liam Hemsworth, Jeff Goldblum, Jessie T. Usher, Bill Pullman','Two decades after the first Independence Day invasion, Earth is faced with a new extra-Solar threat. But will mankinds new space defenses be enough?','English, Mandarin','USA','1 win & 15 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjIyMTg5MTg4OV5BMl5BanBnXkFtZTgwMzkzMjY5NzE@._V1_SX300.jpg',32,'5.3','126,209','$103,137,295.00','https://www.youtube.com/embed/LbduDRH2m2M');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'How to Train Your Dragon',2010,'PG','26 Mar 2010','98 min','Animation, Action, Adventure','Dean DeBlois, Chris Sanders','William Davies (screenplay), Dean DeBlois (screenplay), Chris Sanders (screenplay), Cressida Cowell (book)','Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera','A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.','English','USA','Nominated for 2 Oscars. Another 25 wins & 58 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg',74,'8.2','521,871','$216,900,000.00','https://www.youtube.com/embed/IT_ufPxiXl8');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Terminator 3: Rise of the Machines',2003,'R','02 Jul 2003','109 min','Action, Adventure, Sci-Fi','Jonathan Mostow','James Cameron (characters), Gale Anne Hurd (characters), John Brancato (story), Michael Ferris (story), Tedi Sarafian (story), John Brancato (screenplay), Michael Ferris (screenplay)','Arnold Schwarzenegger, Nick Stahl, Claire Danes, Kristanna Loken','A cybernetic warrior from a post-apocalyptic future travels back in time to protect a 25-year old drifter and his future wife from a most advanced robotic assassin and to ensure they both survive a nuclear attack.','English','USA, Germany, UK','2 wins & 21 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_SX300.jpg',66,'6.4','318,304','$150,252,753','https://www.youtube.com/embed/_cEOqHFrQso');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Guardians of the Galaxy',2014,'PG-13','01 Aug 2014','121 min','Action, Adventure, Sci-Fi','James Gunn','James Gunn, Nicole Perlman, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Bill Mantlo (character created by: Rocket Raccoon), Keith Giffen (character created by: Rocket Raccoon), Jim Starlin (characters created by: Drax the Destroyer,  Gamora,  Thanos), Steve Englehart (character created by: Star-Lord), Steve Gan (character created by: Star-Lord), Steve Gerber (character created by: Howard the Duck), Val Mayerik (character created by: Howard the Duck)','Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel','A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.','English','USA, UK','Nominated for 2 Oscars. Another 50 wins & 96 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg',76,'8.1','746 571','$270,592,504','https://www.youtube.com/embed/b7yOuhI1dzU');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Interstellar',2014,'PG-13','07 Nov 2014','169 min','Adventure, Drama, Sci-Fi','Christopher Nolan','Jonathan Nolan, Christopher Nolan','Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow','A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.','English','USA, UK, Canada, Iceland','Won 1 Oscar. Another 41 wins & 142 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg',74,'8.6','1,036,323','$158,737,441','https://www.youtube.com/embed/Rt2LHkSwdPQ');" +
                    "INSERT INTO MOVIES VALUES (NULL, 'Inception',2010,'PG-13','16 Jul 2010','148 min','Action, Adventure, Sci-Fi','Christopher Nolan','Christopher Nolan','Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy','A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.','English, Japanese, French','USA, UK','Won 4 Oscars. Another 146 wins & 197 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',74,'8.8','1,570,807','$292,568,851','https://www.youtube.com/embed/xitHF0IPJSQ');" +
                "INSERT INTO MOVIES VALUES (NULL, 'The Hobbit: An Unexpected Journey',2012,'PG-13','14 Dec 2012','169 min','Adventure, Fantasy','Peter Jackson','Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay), Guillermo del Toro (screenplay), J.R.R. Tolkien (novel)','Ian McKellen, Martin Freeman, Richard Armitage, Ken Stott','A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.','English','USA, New Zealand','Nominated for 3 Oscars. Another 10 wins & 72 nominations.','https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_SX300.jpg',58,'7.9','666,597','$303,001,229','https://www.youtube.com/embed/SZ6WX0EI31Q');"
            );
            return true;
        } catch let error {
            print(error);
            print(error.localizedDescription)
            return false;
        }
    }

}
